# Generated by Django 5.1.6 on 2025-02-12 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_exercisequestion_question_type_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserResponse',
            new_name='ExerciseResponse',
        ),
    ]
