# Generated by Django 5.1.2 on 2025-03-20 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExerciseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In_Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.enduser')),
            ],
            options={
                'unique_together': {('user', 'exercise')},
            },
        ),
        migrations.CreateModel(
            name='UserResourceProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In_Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.additionalresource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.enduser')),
            ],
            options={
                'unique_together': {('user', 'resource')},
            },
        ),
        migrations.CreateModel(
            name='UserVideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In_Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.enduser')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.videoresource')),
            ],
            options={
                'unique_together': {('user', 'video')},
            },
        ),
    ]
