# Generated by Django 5.1.2 on 2025-03-20 02:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userexerciseprogress_userresourceprogress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='rating_value',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
