# Generated by Django 5.1.6 on 2025-02-18 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_backgroundstyle_background_image'),
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExerciseResponse',
            new_name='UserResponse',
        ),
    ]
