# Generated by Django 5.1.2 on 2025-02-17 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_question_questionnaire_choice_question_questionnaire'),
        ('users', '0002_userresponse_questionresponse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserResponse',
            new_name='Questionnaire_UserResponse',
        ),
    ]
