# Generated by Django 5.1.2 on 2025-03-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_journalentry_date_alter_journalentry_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='coffee',
            new_name='caffeine',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='connected_with_family',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='expressed_gratitude',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='goal_progress',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='outdoors',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='sunset',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
    ]
