# Generated by Django 5.1.2 on 2025-02-20 12:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_stickynote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionresponse',
            name='selected_choice',
        ),
        migrations.AlterField(
            model_name='questionnaire_userresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.enduser'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='rating_value',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
