# Generated by Django 5.1.6 on 2025-02-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='additional_resources',
        ),
        migrations.AddField(
            model_name='module',
            name='additional_resources',
            field=models.ManyToManyField(blank=True, related_name='sections', to='client.additionalresource'),
        ),
    ]
