# Generated by Django 5.1.2 on 2025-03-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='sentiment',
            field=models.IntegerField(choices=[(1, 'Positive'), (-1, 'Negative')], default=1),
        ),
    ]
