# Generated by Django 5.1.2 on 2025-03-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='categories',
            field=models.ManyToManyField(related_name='programs', to='client.category'),
        ),
    ]
