# Generated by Django 5.1.6 on 2025-02-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisequestion',
            name='question_type',
        ),
        migrations.AddField(
            model_name='exercisequestion',
            name='has_blank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercisequestion',
            name='text_after_blank',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercisequestion',
            name='text_before_blank',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('fill_blank', 'Fill in the Blanks'), ('short_answer', 'Short Answer'), ('multiple_choice', 'Multiple Choice')], max_length=20),
        ),
    ]
