# Generated by Django 5.1.2 on 2025-02-08 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='option',
            new_name='option_text',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='option_text',
        ),
        migrations.AddField(
            model_name='option',
            name='question_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='client.questionoption'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_set',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_option', to='client.questionoption'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='QuestionOptions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_options', to='client.option'),
        ),
    ]
