# Generated by Django 5.1.6 on 2025-03-24 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_initial'),
        ('users', '0002_remove_enduser_badges'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
