# Generated by Django 5.1.2 on 2025-02-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_question_questionnaire_choice_question_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
