# Generated by Django 5.1.2 on 2025-02-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_userresponse_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
