# Generated by Django 5.1.6 on 2025-02-12 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_questions', to='client.exercisequestion'),
        ),
        migrations.AlterField(
            model_name='exercisequestion',
            name='question_type',
            field=models.CharField(choices=[('fill_blank', 'Fill in the Blanks'), ('short_answer', 'Short Answer'), ('multiple_choice', 'Multiple Choice')], max_length=20),
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
