# Generated by Django 5.1.6 on 2025-02-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_exercisequestion_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='diagram',
            field=models.ImageField(blank=True, null=True, upload_to='diagrams/'),
        ),
        migrations.AddField(
            model_name='section',
            name='question_position',
            field=models.CharField(choices=[('above', 'Above the Diagram'), ('below', 'Below the Diagram'), ('left', 'Left of the Diagram'), ('right', 'Right of the Diagram')], default='below', max_length=10),
        ),
    ]
