# Generated by Django 5.1.6 on 2025-02-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='section',
        ),
        migrations.RemoveField(
            model_name='module',
            name='program',
        ),
        migrations.RemoveField(
            model_name='section',
            name='module',
        ),
        migrations.AddField(
            model_name='module',
            name='sections',
            field=models.ManyToManyField(related_name='modules', to='client.section'),
        ),
        migrations.AddField(
            model_name='program',
            name='modules',
            field=models.ManyToManyField(related_name='programs', to='client.module'),
        ),
        migrations.AddField(
            model_name='section',
            name='exercises',
            field=models.ManyToManyField(related_name='sections', to='client.exercise'),
        ),
    ]
