# Generated by Django 5.1.2 on 2025-02-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_option_option_option_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='QuestionOptions',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_set',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='question',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Questionnaire',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
    ]
