# Generated by Django 5.1.6 on 2025-02-12 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_section_diagram_section_question_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='question_position',
            new_name='Text_position_from_diagram',
        ),
    ]
