# Generated by Django 5.1.2 on 2025-02-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_backgroundstyle_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='modules',
            field=models.ManyToManyField(related_name='programs', through='client.ProgramModule', to='client.module'),
        ),
    ]
