# Generated by Django 5.1.2 on 2025-02-20 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_program_modules'),
        ('users', '0005_remove_questionresponse_selected_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='categories',
            field=models.ManyToManyField(related_name='programs', to='client.category'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.category'),
        ),
        migrations.AddField(
            model_name='question',
            name='sentiment',
            field=models.IntegerField(choices=[(1, 'Positive'), (-1, 'Negative')], default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('AGREEMENT', 'Agreement Scale'), ('RATING', 'Rating Scale')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
