# Generated by Django 5.1.6 on 2025-02-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_rename_question_position_section_text_position_from_diagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('book', 'Book'), ('podcast', 'Podcast'), ('survey', 'Survey'), ('pdf', 'PDF Document'), ('link', 'External Link')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='section',
            name='Text_position_from_diagram',
        ),
        migrations.AddField(
            model_name='section',
            name='additional_resources',
            field=models.ManyToManyField(blank=True, related_name='sections', to='client.additionalresource'),
        ),
        migrations.AddField(
            model_name='section',
            name='text_position_from_diagram',
            field=models.CharField(choices=[('above', 'Above the Diagram'), ('below', 'Below the Diagram'), ('left', 'Left of the Diagram'), ('right', 'Right of the Diagram')], default='below', max_length=10),
        ),
    ]
