# Generated by Django 5.1.2 on 2025-02-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_program_categories_question_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='max_rating',
        ),
        migrations.RemoveField(
            model_name='question',
            name='min_rating',
        ),
    ]
